name: Build and Push Docker image

on:
  push:
    branches: [feature/build-pipeline]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./k8s_practice/nginx-k8s/k8s/simple-web
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/simple-web:latest 